#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/../config/pipeline_config.sh"

mkdir -p "$IMMICH_APP" "$IMMICH_LIBRARY" "$IMMICH_APP/upload" "$IMMICH_APP/postgres" "$IMMICH_APP/profile" "$IMMICH_APP/backups"

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
	echo "ERROR: Docker + Docker Compose plugin required. Run scripts/01_setup_dependencies.sh first."
	exit 1
fi

if [[ ! -f "$IMMICH_APP/.env" ]]; then
	DB_PASSWORD="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)"
	cat >"$IMMICH_APP/.env" <<EOF
# Generated by media-pipeline scripts/09_setup_immich.sh
UPLOAD_LOCATION=$IMMICH_APP/upload
DB_DATA_LOCATION=$IMMICH_APP/postgres
IMMICH_VERSION=release
DB_PASSWORD=$DB_PASSWORD
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
TZ=${TZ:-Etc/UTC}
EOF
fi

cat >"$IMMICH_APP/docker-compose.yml" <<'YAML'
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /mnt/target_drive/immich_library:/library:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false

volumes:
  model-cache:
YAML

chmod -R a+rX "$IMMICH_LIBRARY"

echo "==> Starting Immich"
cd "$IMMICH_APP"
docker compose up -d

echo "==> Immich containers"
docker compose ps

echo
cat <<EOF
Immich should be available at:
  http://localhost:2283
  http://SERVER_IP:2283

After creating the admin user:
  Administration -> External Libraries -> New External Library
  Add folder path: /library
  Save
  Scan All Library Files

Do NOT use /data as an external library path. /data is Immich's upload folder and Immich rejects it for external libraries.
EOF
